export const TOGGLE_MENU_BAR = "TOGGLE_MENU_BAR";
export const TOGGLE_SEARCH = "TOGGLE_MENU_SEARCH";
export const TOGGLE_MODAL = "TOGGLE_MODAL";
export const CHANGE_SEARCH = "CHANGE_SEARCH";

export const TOGGLE_REPLYCOMMENT = "TOGGLE_REPLYCOMMENT";
export const TOGGLE_FROMREPLYCOMMENT = "TOGGLE_FROMREPLYCOMMENT";

export const TOGGLE_LOADING = "TOGGLE_LOADING";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const REFRESH_TOKEN = "REFRESH_TOKEN";

export const COMMENT_REQUEST = "COMMENT_REQUEST";
export const COMMENT_SUCCESS = "COMMENT_SUCCESS";
export const COMMENT_FAILURE = "COMMENT_FAILURE";

export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";

export const LOG_OUT_USER = "LOG_OUT_USER";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const MESSAGE_FAILURE = "MESSAGE_FAILURE";

export const POST_COMMENT_REQUEST = "POST_COMMENT_REQUEST";
export const POST_COMMENT_SUCCESS = "POST_COMMENT_SUCCESS";
export const POST_COMMENT_FAILURE = "POST_COMMENT_FAILURE";

export const POST_REPLY_COMMENT_REQUEST = "POST_REPLY_COMMENT_REQUEST";
export const POST_REPLY_COMMENT_SUCCESS = "POST_REPLY_COMMENT_SUCCESS";
export const POST_REPLY_COMMENT_FAILURE = "POST_REPLY_COMMENT_FAILURE";

export const FILTER_FILM = "FILTER_FILM";

///////////////////////////////////////////////////////////////////////////////

export const ACT_LIST_FILM_HOME = "ACT_LIST_FILM_HOME";
export const ACT_LIST_FILM_TRENDING = "ACT_LIST_FILM_TRENDING";
export const ACT_LIST_FILM_GENRES = "ACT_LIST_FILM_GENRES";
export const ACT_DETAIL_FILM = "ACT_DETAIL_FILM";
export const ACT_UPCOMING = "ACT_UPCOMING";
export const ACT_LIST_FILM_FICTION = "ACT_LIST_FILM_FICTION";
export const ACT_LIST_FILM_CINEMO = "ACT_LIST_FILM_CINEMO";
export const ACT_LIST_FILM_SIMILAR = "ACT_LIST_FILM_SIMILAR";

export const ACT_LOGIN = "ACT_LOGIN";
export const ACT_LOGIN_AUTO = "ACT_LOGIN_AUTO";
export const ACT_LOGOUT = "ACT_LOGOUT";
export const ACT_REGISTER = "ACT_REGISTER";
export const ACT_SET_TYPE = "ACT_SET_TYPE";

export const ACT_GET_COMMENT = "ACT_GET_COMMENT";
export const ACT_POST_COMMENT = "ACT_POST_COMMENT";
export const ACT_REPLY_COMMENT = "ACT_REPLY_COMMENT";
